# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'theServerSideSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for theServerSideSwift
	pod 'Server_app_iOS_SDK', :path => "../server_app/Server_app_iOS_SDK"
end
